FareShare (copy)/FareShare/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from offerride.views import index
from signin.views import email

urlpatterns = [
	url(r'^$',index),
    url(r'^admin/', admin.site.urls),
    url(r'^offerride/', include('offerride.urls')),
    url(r'^signin/', include('signin.urls'))
    ]


#urlpatterns += staticfiles_urlpatterns()

FareShare (copy)/offerride/urls.py
from django.conf.urls import url
from . import views

app_name = 'offerride'

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^rides/$', views.rides, name='rides'),
    url(r'^addride/$', views.addride, name='addride'),
    url(r'^submitride/$', views.submitride, name='submitride'),
    url(r'^join/$', views.join, name='join'),
    url(r'^addcar/$', views.addcar, name='addcar'),
    url(r'^submitcar/$', views.submitcar, name='submitcar'),
    url(r'^seat/$', views.seat, name='seat'),
    url(r'^maps/$', views.maps, name='maps'),

    
]

FareShare (copy)/signin/urls.py
from django.conf.urls import url

from . import views

app_name = 'signin'

urlpatterns = [
    
    url(r'^registration/$',views.registration, name='registration'),
    url(r'^login/$',views.login, name='login'),
    url(r'^logout/$',views.logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^send/$', views.email,name='email'),



]

FareShare (copy)/offerride/models.py
from django.db import models


"""class Driver(models.Model):
	uname = models.CharField(max_length=250)
	email = models.CharField(max_length=250)
	fname = models.CharField(max_length=250)
	lname = models.CharField(max_length=250)
	psw  = models.CharField(max_length=240)
	def __str__(self):
		return self.uname"""


class Car(models.Model):
	username = models.CharField(max_length=250,default='rnk')
	carseats = models.IntegerField(default=0,null = True)
	color= models.CharField(max_length=240, default='red',null = True)
	carno = models.CharField(max_length=250, default="x",null = True)
	carmodel= models.CharField(max_length=250, default='x',null = True)
	cartype = models.CharField(max_length=250,default='s',null = True)
	def __str__(self):
		return self.carno

class Ride(models.Model):
	#driver = models.ForeignKey(Driver, on_delete=models.CASCADE)
	#driverid = models.CharField(max_length=250, default='rnk')
	username = models.CharField(max_length=250,default='rnk')
	startpoint = models.CharField(max_length=250)
	endpoint = models.CharField(max_length=250)
	ipoint1 = models.CharField(max_length=250)
	ipoint2 = models.CharField(max_length=250)
	date = models.CharField(max_length =250, default='23/3/2019')
	time = models.CharField(max_length =250, default='10:10')
	price = models.IntegerField(default = 0)
	seat = models.IntegerField(default = 1)
	
	def __str__(self):
		return self.startpoint + '-' + self.endpoint
 

FareShare (copy)/offerride/views.py
from django.http import HttpResponse
from django.shortcuts import render,loader
from .models import Ride,Car
from django.contrib.auth.models import User



def index(request):
	return render(request,'offerride/index.html')


def addride(request):
	return render(request,'offerride/addride.html')

def submitride(request):
	print("form is submitted")
	startpoint = request.POST.get("startpoint")
	endpoint = request.POST.get("endpoint")
	ipoint1 = request.POST.get("ipoint2")
	ipoint2 = request.POST.get("ipoint2")
	date = request.POST.get("date")
	time = request.POST.get("time")
	seat = request.POST.get("seat")
	price = request.POST.get("price")
	username = None
	#if request.user.autheticated():
	username = request.user.username
	print(username)	
	ride = Ride(username=username,startpoint=startpoint,endpoint=endpoint,ipoint1=ipoint1,ipoint2=ipoint2,date=date,time=time,seat=seat,price=price)
	ride.save()
	print("saved")
	return render(request,'offerride/addride.html')

prev=0
def join(request):
	all_rides = Ride.objects.all()
	template = loader.get_template('offerride/rides.html')
	context = {'all_rides': all_rides}
	reduce_seat = all_rides.get(pk=request.POST['join'])
	print(reduce_seat.pk)
	if reduce_seat.seat >= 1:
		reduce_seat.seat = reduce_seat.seat - 1
		reduce_seat.save()
	return  HttpResponse(template.render(context,request))

def addcar(request):
	return render(request,'offerride/addcar.html')


def submitcar(request):
	print(" Car form is submitted")
	carno = request.POST.get("carno")
	carmodel = request.POST.get("carmodel")
	color = request.POST.get("color")
	cartype = request.POST.get("cartype")
	carseats=request.POST.get("carseats")
	username = None
	#if request.user.autheticated():
	username = request.user.username
	car = Car(username=username,carseats = carseats,color= color, carno = carno, carmodel=carmodel, cartype=cartype)
	car.save()
	print("Car saved")
	return HttpResponse("SAVED")


def rides(request):
	startpoint = request.POST.get("startpoint")
	endpoint = request.POST.get("endpoint")
	date = request.POST.get("date")
	all_rides = Ride.objects.all()
	context = {'all_rides': all_rides,
				'startpoint' : startpoint,
				'endpoint' : endpoint,
				'date' : date,
				}

	return render(request,'offerride/rides.html',context)

def seat(request):
    return render(request,'offerride/seat.html')


def maps(request):
    return render(request,'offerride/maps.html')

FareShare (copy)/offerride/templates/offerride/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <!-- Title -->
    <title>FareShare</title>

    

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap-datepicker.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/imagesloaded.pkgd.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/isotope.pkgd.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/jarallax.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/jarallax-video.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/jquery.countdown.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/jquery.counterup.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/jquery.easing.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/jquery.magnific-popup.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/jquery.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/jquery.nice-select.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/jquery-ui.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/owl.carousel.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/popper.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/roberto.bundle.js' %}">
    <link rel="stylesheet" href="{% static 'js/waypoints.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/wow.min.js' %}">

    <link rel="stylesheet" href="{% static 'js/default-assets/active.js' %}">
    <link rel="stylesheet" href="{% static 'js/default-assets/avoid.console.error.js' %}">
    <link rel="stylesheet" href="{% static 'js/default-assets/classy-nav.js' %}">
    <link rel="stylesheet" href="{% static 'js/default-assets/jquery.scrollup.min.js' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/default-assets/classy-nav.css' %}">
    <link rel="icon" href="{% static '/img/bg-img/13.jpg' %}">
     <link rel="icon" href="{% static '/img/bg-img/14.jpg' %}">
     <link rel="icon" href="{% static '/img/bg-img/15.jpg' %}">
     <link rel="icon" href="{% static '/img/bg-img/16.jpg' %}">
     <link rel="icon" href="{% static '/img/bg-img/17.jpg' %}">
     <link rel="icon" href="{% static '/img/bg-img/18.jpg' %}">
   <link rel="icon" href="{% static '/img/core-img/icon-1.png' %}">
    <link rel="icon" href="{% static '/img/core-img/icon-2.png' %}">
    <link rel="icon" href="{% static '/img/core-img/icon-3.png' %}">
    <link rel="icon" href="{% static '/img/core-img/icon-4.png' %}">

    <link rel="icon" href="{% static '/img/core-img/logo.png' %}">

    <link rel="icon" href="{% static '/img/core-img/logo2.png' %}">

    <link rel="icon" href="{% static '/img/core-img/Logo.png' %}">
    <link rel="stylesheet" href="{% static 'seat.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>

<body>
    <!-- Preloader -->
    <div id="preloader">
        <div class="loader"></div>
    </div>
    <!-- /Preloader -->

    <!-- Header Area Start -->
    <header class="header-area">
        <!-- Search Form -->
        <div class="search-form d-flex align-items-center">
            <div class="container">
                <form action="index.html" method="get">
                    <input type="search" name="search-form-input" id="searchFormInput" placeholder="Type your keyword ...">
                    <button type="submit"><i class="icon_search"></i></button>
                </form>
            </div>
        </div>

        <!-- Top Header Area Start -->
        <div class="top-header-area">
            <div class="container">
                <div class="row">

                    <div class="col-6">
                        <div class="top-header-content">
                            
                            <a href="#"><i class="icon_mail"></i> <span>fareShare@gmail.com</span></a>
                        </div>
                    </div>

                    <div class="col-6">
                        <div class="top-header-content">
                            <!-- Top Social Area -->
                            <div class="top-social-area ml-auto">
                                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-tripadvisor" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Top Header Area End -->

        <!-- Main Header Start -->
        <div class="main-header-area">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Classy Menu -->
                    <nav class="classy-navbar justify-content-between" id="robertoNav">

                        <!-- Logo -->
                        <a class="nav-brand" href="index.html"><img src="{% static './img/core-img/logo.png' %}" alt=""></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">
                            <!-- Menu Close Button -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>
                            <!-- Nav Start -->
                            <div class="classynav">
                                 <ul id="nav">
                                    <li class="active"><a href="{% url 'offerride:index' %}">Home</a></li>
                                    {% if user.is_authenticated %}
	{% if user.is_superuser %}
					<li><a href="{% url 'signin:email' %}"><span class="glyphicon glyphicon-send"></span> Send</a></li>
</li>
	</li>				{% endif %}
                                        <li><a href="{% url 'signin:logout' %}">Log Out</a></li>
                                        <li><a href="{% url 'offerride:addride' %}">Offer Ride</a></li>
                                        <li>


                                <!-- Book Now -->
                                <div class="book-now-btn ml-3 ml-lg-5">
                                    <a href="#">Book Ride <i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>
                                </div>

                                </li>
                                
                                    <li class="glyphicon glyphicon-bell"></li>
                                <li>
                                     <a href="{% url 'signin:profile' %}"><i class="glyphicon glyphicon-user" aria-hidden="true">My Profile</i></a></li>
                                   {% else %}
                                    <li><a href="{% url 'signin:login' %}">Log In</a></li>
                                    
                                        <li><a href="{% url 'signin:registration' %}">Sign Up</a></li>
                                        <li> <div class="search-btn ml-4">
                                        <i class="fa fa-search" aria-hidden="true"></i>
                                    </div></li>
                               
                                    {% endif %}
                                </ul>
                            </div>
                            <!-- Nav End -->
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Area End -->




    {% block body %}
    {% endblock %}




 <!-- Footer Area Start -->
    <footer class="footer-area section-padding-80-0">
        <!-- Main Footer Area -->
        <div class="main-footer-area">
            <div class="container">
                <div class="row align-items-baseline justify-content-between">
                    <!-- Single Footer Widget Area -->
                    <div class="col-12 col-sm-6 col-lg-3">
                        <div class="single-footer-widget mb-80">
                            <!-- Footer Logo -->
                            <a href="#" class="footer-logo"><img src="{% static 'img/core-img/Logo.png' %}" alt=""></a>

                            <h4>+12 345-678-9999</h4>
                            <span>fareshare@gmail.com</span>
                            
                        </div>
                    </div>

                    
                    <!-- Single Footer Widget Area -->
                    <div class="col-12 col-sm-4 col-lg-2">
                        <div class="single-footer-widget mb-80">
                            <!-- Widget Title -->
                            <h5 class="widget-title">Links</h5>

                            <!-- Footer Nav -->
                            <ul class="footer-nav">
                                <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i> About Us</a></li>
                                <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i> FAQs</a></li>
                            </ul>
                        </div>
                    </div>

                    <!-- Single Footer Widget Area -->
                    <div class="col-12 col-sm-8 col-lg-4">
                        <div class="single-footer-widget mb-80">
                            <!-- Widget Title -->
                            <h5 class="widget-title">Tell Us about your exprience</h5>
                           

                            <!-- Newsletter Form -->
                            <form action="index.html" class="nl-form">
                                <input type="email" class="form-control" placeholder="Enter your email...">
                                <button type="submit"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Copywrite Area -->
        <div class="container">
            <div class="copywrite-content">
                <div class="row align-items-center">
                    <div class="col-12 col-md-8">
                        <!-- Copywrite Text -->
                        <div class="copywrite-text">
                            <p>
                             FareShare is the  carpooling plateform. Forget going into the city to get out of town. We connect people together, making it possible to travel literally anywhere, directly. 
                            </p>
                        </div>
                    </div>
                    <div class="col-12 col-md-4">
                        <!-- Social Info -->
                        <div class="social-info">
                            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Area End -->

    <!-- **** All JS Files ***** -->
    <!-- jQuery 2.2.4 -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Popper -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- All Plugins -->
    <script src="{% static 'js/roberto.bundle.js' %}"></script>
    <!-- Active -->
    <script src="{% static 'js/default-assets/active.js' %}"></script>

</body>

</html>

FareShare (copy)/offerride/templates/offerride/maps.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Waypoints in Directions</title>
    <style>
      #right-panel {
        font-family: 'Roboto','sans-serif';
        line-height: 30px;
        padding-left: 10px;
      }

      #right-panel select, #right-panel input {
        font-size: 15px;
      }

      #right-panel select {
        width: 100%;
      }

      #right-panel i {
        font-size: 12px;
      }
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 100%;
        float: left;
        width: 70%;
        height: 100%;
      }
      #right-panel {
        margin: 20px;
        border-width: 2px;
        width: 20%;
        height: 400px;
        float: left;
        text-align: left;
        padding-top: 0;
      }
      #directions-panel {
        margin-top: 10px;
        background-color: #FFEE77;
        padding: 10px;
        overflow: scroll;
        height: 174px;
      }
    </style>
  </head>
  <body>

    <div id="map"></div>
    <div id="right-panel">
    <div>
    <b>Start:</b>
    <input type="text" id="start">
    <br>
    <b>Waypoints:</b> <br>
    <input type="text" id="w1">
    <input type="text" id="w2">
    <br>
    <b>End:</b>
    <input type="text" id="end">
    <br>
      <input type="submit" id="submit">
    </div>
    <div id="directions-panel"></div>
    </div>
    <form action="{ % url {'offerride:addride'} %}">
        <button type="submit">Return</button>
    </form>
    <script>
      function initMap() {
        var directionsService = new google.maps.DirectionsService;
        var directionsDisplay = new google.maps.DirectionsRenderer;
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 6,
          center: {lat: 41.85, lng: -87.65}
        });
        directionsDisplay.setMap(map);

        document.getElementById('submit').addEventListener('click', function() {
          calculateAndDisplayRoute(directionsService, directionsDisplay);
        });
      }

      function calculateAndDisplayRoute(directionsService, directionsDisplay) {
        var waypts = [];
        var wp1 = document.getElementById('w1');
        var wp2= document.getElementById('w2');
        //var wp3 = document.getElementById('w3'); 
        
        waypts.push({
              location:  ''+document.getElementById('w1').value,
              stopover: true
            });

        waypts.push({
              location: ''+document.getElementById('w2').value,
              stopover: true
            });

     

        directionsService.route({
          origin: document.getElementById('start').value,
          destination: document.getElementById('end').value,
          waypoints: waypts,
          optimizeWaypoints: true,
          travelMode: 'DRIVING'
        }, function(response, status) {
          if (status === 'OK') {
            directionsDisplay.setDirections(response);
            var route = response.routes[0];
            var summaryPanel = document.getElementById('directions-panel');
            summaryPanel.innerHTML = '';
          } else {
            window.alert('Directions request failed due to ' + status);
          }
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDYTtaY3HUsCFCzWT5ViJFzAZtP3ieUpg4
&callback=initMap">
    </script>
  </body>
</html>

FareShare (copy)/offerride/templates/offerride/rides.html
{% extends 'offerride/base.html' %}

 {% block body %}
	<form action="{% url 'offerride:join' %}" method="post">
         {% csrf_token %}
	{% for ride in all_rides %}
        <div class="w3-container" align ="center" style="padding-top: 25px;">
          <div class="w3-card-4" style="width:70%">
            <header class="w3-container w3-light-grey">
                <h3> {{ ride.startpoint }} <b>TO</b> {{ ride.endpoint }}</h3>
            </header>
            <div class="w3-container">
              <p> Via : {{ ride.ipoint1 }} , {{ride.ipoint2 }} {{ forloop.counter }}</p>
              <p> Date : {{ ride.date }} &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Time : {{ride.time }}</p>
				<p> Price : {{ ride.price }} &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Available Seats : {{ride.seat }}</p>
              <!--<img src="car.jpg" alt="Avatar" class="w3-left w3-margin-right" style="width:100px"> -->
            
            
            <a href="{% url 'signin:email' %}">
            <button class="w3-button w3-block w3-dark-grey" type="submit"  value="{{ forloop.counter }}" name="join">JOIN</button></a>

            <p>{{rides.username}}
            </p>
          </div>
          </div>
        </div>
	</form>

  <form action="{% url 'offerride:seat' %}" method="post">
    {% csrf_token %}
    <div class="w3-container" align ="center" style="padding-top: 25px;">
        <div class="w3-card-4" style="width:70%">
          <button class="w3-button w3-block w3-dark-grey" type="submit"  value="{{ forloop.counter }}" name="join">select seat</button>
        </div>
    </div>
  </form>

  {% endfor %}

{% endblock %}


<!--<h3>Current rides available.</h3>
		<ul>
			{% for ride in all_rides %}
				{% if startpoint == ride.startpoint or endpoint == ride.endpoint or endpoint == ride.ipoint1 or endpoint == ride.ipoint2 %}
					<li><a href="#">{{ride.startpoint}}-{{ride.endpoint}}</a></li>
			{% endif %}
			{% endfor %}


		</ul>

		<h3>You don't have rides</h3>-->

FareShare (copy)/offerride/templates/offerride/seat.html
{% extends 'offerride/base.html' %}


{% block body%}

<form action="{% url 'offerride:rides' %}">
<div class="plane">
  <div class="cockpit">
    <h1>Please select a seat</h1>
  </div>
  <div class="exit exit--front fuselage">
    
  </div>
  

    <ol class="cabin fuselage">
      <li class="row row--1">
        <ol class="seats" type="A">
          <li class="seat">
            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
            <input type="checkbox" />
           Vacant
          </li>
          <li class="seat">
            <input type="checkbox"/>
          Vacant
          </li>
          <li class="seat">
            <input type="checkbox" disabled />
            occoupied(Female)
          </li>
          
         </ol>
       </li>
     <li>
                              <div class="form-group">
                                  
                                  <button type="submit" class="btn roberto-btn w-100">Select Seat</button>
                              </div>
                            </li>
        
    </ol>
    <div class="exit exit--back fuselage">
      
    </div>
  </div>
</form>
{% endblock %}